项目整合/python项目/PackFiles/my_django/my_django/myproject/accounts/urls.py
from django.conf.urls import url
from . import views as accounts_views
from django.contrib.auth import views as auth_views
from boards import views
urlpatterns = [

    url(r'^register/$',accounts_views.register,name='register'), # 注册
    url(r'^login/$',auth_views.LoginView.as_view(template_name='login.html'),name='login'), # 登录
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'), # 注销
    url(r'^settings/password/$',auth_views.PasswordChangeView.as_view(template_name='password_change.html'),name="password_change"),
    url(r'^settings/password/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name="password_change_done")
]

项目整合/python项目/PackFiles/my_django/my_django/myproject/boards/urls.py
from django.urls import path
from django.conf.urls import url

from .views import *
from . import views
urlpatterns = [

    url(r'^boards/(?P<pk>\d+)/$',views.board_topics,name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/add/$',views.new_topic,name='new_topic'),
    path('',views.BoardListView.as_view(),name='home'), #

]

项目整合/python项目/PackFiles/my_django/my_django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from boards.views import *
from django.conf.urls import url
from boards import views
urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include(('boards.urls','boards'), namespace='boards')),
    path('',include(('accounts.urls','accounts'),namespace='accounts')),
    path('',include(('theblog.urls','theblog'),namespace='theblog')),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$',views.topic_posts,name="topic_posts"),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$',views.reply_topic,name="reply_topic"),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='edit_post'),

]

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/add_topic.html
{% extends 'base.html'%}

{% block title%}Start a New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}


<!--正文开始-->
{% block content %}
    <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">发表</button>
  </form>


{% endblock%}
<!--正文结束-->

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %} {% endblock %} <!--这里添加一些特定页面的css样式-->
</head>
<body>
{% block body %} <!--这里添加特定的主体-->
    <!--导航条开始-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'boards:home' %}">首页</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href="#">我的账户</a>
                                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">修改密码</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">注销</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">登录</a>
                        <a href="{% url 'accounts:register' %}" class="btn btn-primary ml-2">注册</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>
    <!--导航条结束-->


    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}

            {% endblock %}
        </ol>
        {% block content %}

        {% endblock %}
    </div>
{% endblock body %}  <!--这里添加特定的主体结束-->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css'%}">
{% endblock %}
<!--主体开始-->
{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'boards:home' %}">Django Boards</a>
        </h1>

        {% block content %}

        {% endblock %}
    </div>
{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}


{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a>
    </li>
    <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }} </a></li>
    <li class="breadcrumb-item active">Edit post</li>
{% endblock %}



{% block content %}
    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">保存-修改</button>
        <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
    </form>
{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}


{% block content %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Board</th>
                <th>Posts</th>
                <th>Topics</th>
                <th>Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="align-middle">{{ board.get_posts_count }}</td>
                    <td class="align-middle">{{ board.topics.count }}</td>
                    <td class="align-middle">
                        {% with post=board.get_last_post %}
                            {% if post %} <!--如果有post-->
                                <small>
                                    <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
                                        By {{ post.created_by.username }} at {{ post.created_at}}
                                    </a>
                                </small>
                            {% else %}
                                <small class="text-muted">
                                    <em>No posts yet.</em>
                                </small>
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}


项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/login.html
{% extends 'base_accounts.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}
<!--特定样式结束-->

{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4"><a href="{% url 'boards:home' %}">Django Boards</a></h1>
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">登录</h3>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            {% include 'includes/form.html' %}
                            <button type="submit" class="btn btn-primary">登录</button>
                        </form>
                    </div>
                    <div class="card-footer text-muted text-center">New to Django Boards? <a href="{% url 'accounts:register' %}">注册新用户</a></div>
                </div>
                <div class="text-center py-2">
                    <small>
                        <a href="#" class="text-muted">忘记了您的密码?</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/password_change.html
{% extends 'base.html' %}
{% block title %}Change password{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">修改-密码</li>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">修改密码</button>
            </form>
        </div>
    </div>
{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/password_change_done.html
{% extends 'base.html' %} {% block title %}Change password successful{% endblock %} {% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:password_change' %}">Change password</a></li>
    <li class="breadcrumb-item active">Success</li> {% endblock %} {% block content %}
    <div class="alert alert-success" role="alert"><strong>Success!</strong> Your password has been changed!</div>
    <a href="{% url 'boards:home' %}" class="btn btn-secondary">Return to home page</a> {% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/register.html
{% extends 'base_accounts.html' %}
{% block title %}Sign up to Django Boards{% endblock %}
<!--特定样式结束-->

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">注册</h3>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-primary">创建用户</button>
                    </form>
                </div>
                <div class="card-footer text-muted text-center">已经有账户了<a href="{% url 'accounts:login' %}">登录</a></div>
            </div>
        </div>
    </div>
{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post a reply{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">回复</li>
{% endblock %}

{% block content %}

  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">添加-回复</button>
  </form>

  {% for post in topic.posts.all %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at }}</small>
          </div>
        </div>
        {{ post.message }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}


{% block content %}
    <div class="mb-4">
        <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">回复</a>
    </div>
    {% for post in topic.posts.all %}
        <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
            {% if forloop.first %}
                <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
            {% endif %}
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{% static 'img/avatar.png' %}" alt="{{ post.created_by.username }}" class="w-100">
                        <small>Posts: {{ post.created_by.posts.count }}</small>
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.message }}
                        {% if post.created_by == user %}
                            <div class="mt-3">
                                <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}" class="btn btn-primary btn-sm" role="button">编辑</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

项目整合/python项目/PackFiles/my_django/my_django/myproject/templates/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">创建新话题</a>
  </div>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
          <td><a href="{% url 'topic_posts' board.pk topic.pk %}">{{ topic.subject }}</a></td>
          <td>{{ topic.starter.username }}</td>
          <td>{{ topic.replies }}</td>
          <td>{{ topic.views }}</td>
          <td>{{ topic.last_update }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}